### ISSUE TITLE
Accidentally filing bugs under wrong repo way too easy

### ISSUE THREAD

**Issue by schwa** [Me1000/issues#123]
I'd rather have a repo picker (maybe parent VC of issues VC) than the repo tab bar.

It's way too easy to file bugs under the wrong repo

**Comment by schwa** [comment]
And by way too easy I mean way too fucking easy.

A "move issue from repo to repo" function might be handy too.

**Comment by Me1000** [comment]
Github doesn't provide a way to delete issues, :(

**Comment by schwa** [comment]
Alright. Forget the move issue. But the initial problem still stands. I think this is a major UI oops. Going to be serious problem IMO.

**Comment by Me1000** [comment]
I'll see what I can do about making it more pronounced which repo lure posting to.

**Comment by Me1000** [comment]
Also, I had thought about getting rid of the tabs at the top, and making the repos live in the table view.... Then you'd dive into the issues from there... Thoughts? I may make your issue worse...

**Comment by schwa** [comment]
Well - I tend to focus on one repo at once. I do not bounce between repos frequently enough that the tab bar makes any sense to me.

I'd rather the repos and issues were in a two level navigation stack in the split view
s master view and the tab bar space was used for something else...

Even if you do bounce between repos a lot - hitting back in the nav bar and picking a new repo is pretty quick.

But yeah issues in tab bar and repos in table view is bad. There are more issues that repos - and for folks with a single repo they care about it'll suck big time.

**Comment by kgn** [comment]
I second the two level navigation, tabs(as they appear in this app) are not a common iOS thing. This confused me at first, I didn't expect multiple repos to be supported this way.

**Comment by Me1000** [comment]
This should be a little more apparent now in 1.5. \n\nClosing
