### ISSUE TITLE
Adding milestone and/or labels deletes issue contents

### ISSUE THREAD

**Issue by tonyarnold** [Me1000/issues#129]
I've seen this quite a bit, and sadly it's just happened with a client issue. Not sure what I can provide to help track this down, but let me know.

**Comment by Me1000** [comment]
This is fixed in the final version. Apologies for this, I thought I had it nailed down in a previous beta, but it turns out there was a 2nd issue causing it.

**Comment by tonyarnold** [comment]
Thanks Randy — I've just installed 1.0 :)

**Comment by Me1000** [comment]
Please let me know if you see it again. I can't believe I missed it for so many betas (I actually think it might have been a regression), but I've tested it pretty heavily recently.

**Comment by tonyarnold** [comment]
Will do :)
