### ISSUE TITLE
Milestone filter

### ISSUE THREAD

**Issue by kgn** [Me1000/issues#131]
I use milestones a lot to filter my issues into chunks of work, it would be great to be able to filter on milestones.

**Comment by Me1000** [comment]
Go to the search, above the keyboard is button bar, tap the milestone button and you should see your milestones which you can filter by... I'm redesigning a lot of stuff, hopefully this will be more up front in the future.

**Comment by Me1000** [comment]
Fixed in 1.5 which was submitted to the app store today. Closing...\n\nThanks

**Comment by kgn** [comment]
Great can't wait for the update!

Did you close this in BugHub? If so the newlines are escaped.

> Closing...\n\nThanks
