### ISSUE TITLE
Add button only shows public repos

### ISSUE THREAD

**Issue by kgn** [Me1000/issues#132]
The first repo I picked was a private one. When I went to add another repo with the plus button all I see are my public repos.

**Comment by Me1000** [comment]
Oh, strange. this is definitely a regression. I'll look into it.

**Comment by dbrajkovic** [comment]
Confirmed. I can't add any private repos I have access to after the initial screen.  I'd like to be able that initial checklist again.

**Comment by Me1000** [comment]
This issue is now fixed, and will be in the next release!

**Comment by Me1000** [comment]
Please confirm this is fixed in the latest release.

**Comment by kgn** [comment]
I can see my private repos! But now all public repos show up twice.

**Comment by Me1000** [comment]
Yeah, for some reason I didn't catch that bug before I submitted the latest update... I submitted 1.0.2 yesterday right after the update was approved, which fixes that issue and some more crashing issues. 

Thanks
