### ISSUE TITLE
Checkmark (complete?) icon disabled but looks enabled.

### ISSUE THREAD

**Issue by dbrajkovic** [Me1000/issues#134]
For a repo such as this one, the checkmark doesn't look any different whether the current user can close the ticket or not. Tapping on it if one doesn't have the right to close, but perhaps the user thinks he does, makes it seem as if the button doesn't work.

**Comment by Me1000** [comment]
Note for self: this applies to all buttons. If a user cannot manage the issue the buttons should probably just be completely hidden.

**Comment by Me1000** [comment]
Fixed in 1.5
