### ISSUE TITLE
Can't swipe off master view

### ISSUE THREAD

**Issue by bobspryn** [Me1000/issues#137]
I switched to a vertical view and did the swiping from off the side of the bezel to show the list of issues for a repository. I can't seem to swipe it back off. OS 5.1

**Comment by GiK** [comment]
See issue #136 - swipe right-to-left on master view's nav bar to dismiss.

**Comment by Me1000** [comment]
Swipe the top of the sidebar to hide it, I'm looking into ways to make this more apparent.

**Comment by Me1000** [comment]
Closing as a dupe of #136
