### ISSUE TITLE
Can't see all orgs

### ISSUE THREAD

**Issue by demonbane** [Me1000/issues#138]
I'm a member of the GitHub organization, but BugHub doesn't seem to realize it. It shows all of my other orgs just fine though.

**Comment by Me1000** [comment]
Hmmm, strange... Do you know if there is something different about the GitHub org? I'm using the standard organization API:

A GET to /user/orgs

**Comment by Me1000** [comment]
I was able to work with Danny Greg to get this fixed. It'll be shipped with the 1.5 update soon.

**Comment by Me1000** [comment]
1.5 was submitted to the app store today with the fix. Closing.\n\nThanks!
