### ISSUE TITLE
Repos aren't removed from the tab bar upon restarting the application

### ISSUE THREAD

**Issue by rbright** [Me1000/issues#141]
In order to reproduce the bug...

Load the application from a fresh install.
Select a repository from the provided list.
On the following screen, select the 'Add' button and add another repository.
Click-and-hold on the unselected tab and remove it.
Drop to the home screen and kill the application.
Open the application again.
Once the application has been reentered, the removed tab will still be present in the list. Since the application resumes with its previous state upon reload, there appears to be no one to truly remove a repository from your tab bar.

**Comment by Me1000** [comment]
Fixed in 1.5

**Comment by Me1000** [comment]
Closing.. 1.5 should make it to the app store in a week after review. \n\nCheers
