### ISSUE TITLE
Able to add repository that does not have Issues enabled

### ISSUE THREAD

**Issue by rbright** [Me1000/issues#143]
Upon initially loading the application, I am presented with a list containing all of my public and private repositories. Since not all of these repositories have Issues enabled, the tab stalls when attempting to load them.

The 'Add New Repository' dialog filters these Issue-less repositories from its list, but the original dialog does not.

**Comment by Me1000** [comment]
It was fixed with the build I submitted last night :)

**Comment by Me1000** [comment]
Update is in the app store
