### ISSUE TITLE
Repositories list is difficult to scan with Lock icon

### ISSUE THREAD

**Issue by joehoyle** [Me1000/issues#160]
I have a mixture of private and public repos. Viewing them in the Repositories drop down is a bit jointed feeling. Perhaps it would look more natural if the lock icon were on the right, so all the repo names would line up on the left.

Hope this isn't a dupe, I looked through and didn't find this mentioned anywhere else.

**Comment by Me1000** [comment]
Agreed :)

**Comment by Me1000** [comment]
Fixed in next build
