### ISSUE TITLE
Can not create issue with a quote in the content

### ISSUE THREAD

**Issue by joehoyle** [Me1000/issues#164]
Sorry about the test issue - this was because it is not letting me create issues with double quotes in the content. After a process of illumination this is what I honed in on!

I get a can not save alert and some other non-descript error alert

**Comment by Me1000** [comment]
I'm going to spend the night rewriting the code that escapes strings... You'd think this would be a solved problem. apologies in advanced for any cussing you see from me in the next few hours. :P

**Comment by Me1000** [comment]
Please verify this is fixed in the latest update
