### ISSUE TITLE
Removed repositories aren't persisted

### ISSUE THREAD

**Issue by koraktor** [Me1000/issues#168]
Once added to the list it seems like you're unable to remove a repository persistently. I'm able to remove repositories and they will disappear for the current session (i.e. as long as the app's memory isn't freed). Once BugHug loads again they will reappear.

**Comment by Me1000** [comment]
This is fixed in the 1.5 update which should show up on the app store in about a week

**Comment by koraktor** [comment]
Sounds good. Thanks for the quick reply.

**Comment by koraktor** [comment]
I just installed 1.5 and can verify that this is working now.

**Comment by Me1000** [comment]
Awesome thanks! Hope you enjoy 1.5!
