### ISSUE TITLE
Initially displayed issue

### ISSUE THREAD

**Issue by eliaskg** [Me1000/issues#171]
After deleting and re-installing the latest RC1 I added a personal repo. After selecting it the following issue was displayed:

![](http://f.cl.ly/items/3j2O0r42312G3h1b0E0I/2012-04-08%20at%2000:04.png)

**Comment by Me1000** [comment]
man, I keep forgetting to comment those lines out. It'll be fixed in the update I submitted today. Thanks!

**Comment by Me1000** [comment]
Closed with today's update
