### ISSUE TITLE
App crashes when saving

### ISSUE THREAD

**Issue by eliaskg** [Me1000/issues#172]
I can't create any issues with the latest RC1. The app crashes every time I tap the save button. Tried to re-install it but that doesn't change anything. ipad2 / iOS 5.1

**Comment by Me1000** [comment]
You editing an issue or creating a new one?

**Comment by Me1000** [comment]
alright, I'm getting the same thing... hmmm, thanks

**Comment by Me1000** [comment]
This is fixed in the latest update I submitted today. Thanks!

**Comment by Me1000** [comment]
Update has just been approved. closing
