### ISSUE TITLE
Comments \n are not escaped properly

### ISSUE THREAD

**Issue by Me1000** [Me1000/issues#175]
new line characters show up as the characters \n

**Comment by koraktor** [comment]
See #176. It was created with BugHub 1.5.1.\n\nAdditionally, the slashes in the URL have been escaped, so there are probably more characters that will be escaped.

**Comment by Me1000** [comment]
Ah, good catch. I'll resubmit the new version that fixes both issues.

**Comment by koraktor** [comment]
Nice.

PS: I edited the other issue, so it's readable again.

**Comment by Me1000** [comment]
Apple has approved my request for expedited review. Hopefully we'll see this update today or tomorrow instead of friday!

**Comment by Me1000** [comment]
Fix has landed on the App Store. Closing
