### ISSUE TITLE
Wrong cross issue references

### ISSUE THREAD

**Issue by PetrKaleta** [Me1000/issues#186]
If you mention issue id in issue description, its visually recognized, but reference is wrong => app will load wrong issue detail after tapping on reference link...

**Comment by Me1000** [comment]
Thanks for reporting this. I'll check it out!

**Comment by Me1000** [comment]
I submitted an update today which significantly simplifies the code for locating those issues. I believe this will resolve your issue.

**Comment by Me1000** [comment]
Fix should be on the app store now
