### ISSUE TITLE
Backslashes are stripped

### ISSUE THREAD

**Issue by koraktor** [Me1000/issues#187]
Looking at koraktor/steam-condenser#159 it seems that backslashes are stripped from messages.

**Comment by Me1000** [comment]
You're on the latest version?

**Comment by koraktor** [comment]
Sure, I guess this might be related to the escaping bug fixed in the last version.

**Comment by Me1000** [comment]
Found the issue. Luckily there was no data loss in this instance. It was just an issue of the backslash character being stripped when displayed in BugHub. This fix will be in the next release!

**Comment by Me1000** [comment]
Fix should be on the app store now

**Comment by koraktor** [comment]
Works, thanks.
