### ISSUE TITLE
Unable to navigate private projects

### ISSUE THREAD

**Issue by guidomb** [Me1000/issues#192]
I cannot navigate my private projects issues.

**Comment by Me1000** [comment]
Can you be more specific? Are you unable to locate your private repos?

**Comment by marijn** [comment]
I have no problem with this.

**Comment by guidomb** [comment]
After I downloaded the last version of the app I had no problems. Thanks!

| Guido Marucci Blas |

**Comment by Me1000** [comment]
Great, thank you!
