### ISSUE TITLE
Doesn't work with private repos?

### ISSUE THREAD

**Issue by skylar** [Me1000/issues#206]
I tried logging out then back in after adding a private repo but it didn't show up in my list

**Comment by grouchal** [comment]
This works fine for me

**Comment by Me1000** [comment]
Are these personal private repos with issues turned on? Or are they shared private repos/organization private repos? And please confirm that issues are indeed enabled on these repos.

**Comment by skylar** [comment]
Hey, I just checked again and it was working now. Perhaps it was some kind of delay in the GitHub API.  I had signed up for private repos less than an hour before testing in the app.

**Comment by Me1000** [comment]
Cool, thanks for the follow up. Please let me know if you have any more issues!
