### ISSUE TITLE
Comments appear in a small frame when written in top left

### ISSUE THREAD

**Issue by grouchal** [Me1000/issues#207]
This could be an ios6 problem but when I add a comment to an issue there is a tiny box to enter it in, I suppose it could also be a retina display issue, but is quite annoying whatever!

**Comment by Me1000** [comment]
Definitely sounds like an iOS 6 issue. I'll see what I can do for you in an upcoming release though. Thanks!

**Comment by koraktor** [comment]
I can confirm this on a iPad (3rd generation) with iOS 6.

**Comment by Me1000** [comment]
Can you confirm this is still an issue with the GM?

**Comment by grouchal** [comment]
Yes this still happens on and iPad 3 with ios6 GM , this very comment is being displayed in a 1x1 inch box in the top left corner of the comment on issue overlay

**Comment by Me1000** [comment]
Hmm, interesting. I either don't understand the issue or I just can't reproduce it. Mind emailing me a screenshot, just so I can confirm what I'm looking for? 

Randy.luecke [at] me [dot] com.

**Comment by besi** [comment]
Had this on an Ipad2 3G with iOS6.0

**Comment by Me1000** [comment]
awesome, that helps a lot! Thanks!

**Comment by codker** [comment]
This happens on iPad mini 6.0.1 too. BugHub 1.5.5

**Comment by joshschumacher** [comment]
I am seeing this issue as well. iOS 6.0.1 on 3rd gen iPad running the current AppStore. Here is a screenshot that gives you a sense of the boundaries - https://www.dropbox.com/s/ht7hpyh2qw6ssrz/Photo%20Dec%2015%2C%2012%2006%2051%20AM.png

**Comment by Me1000** [comment]
Just submitted this fix to the App Store! 

Thanks for your patience!

**Comment by Me1000** [comment]
The updated should be on the app store now! 

Thanks everyone for your patience.

**Comment by koraktor** [comment]
In the current version available from the AppStore the text field is now wider than the modal view.
