### ISSUE TITLE
Continues crash

### ISSUE THREAD

**Issue by xu-cheng** [Me1000/issues#228]
This app on my iPad 3 (iOS 6.1) just crashes all the time. It crashes when I add repo, switch repo, refresh issue list etc. Sometimes it crashes on its own without any operation.

**Comment by jelledelaender** [comment]
Got the same issue, crashes every 5 seconds. Emailed the dev crashlogs,
so far no responds :(

**Comment by Me1000** [comment]
please confirm this is still an issue after the update released today.

**Comment by jelledelaender** [comment]
It's crashing less but still crashing a lot.

Seems like thread-issues. Often it crashes at starttime/loadtime, otherwise when I select a repo or try to add one.

Jelle,
