### ISSUE TITLE
Missing private repo

### ISSUE THREAD

**Issue by shanemcd** [Me1000/issues#229]
I am a member of a team on a private repo created by another organization. This repo is not showing up. Do you not support teams within private repos?

**Comment by Me1000** [comment]
It should be supported, other people have reported this a couple times… I'll see if I can get a fix out for it very soon!
- Randy

**Comment by joelparsons** [comment]
I'm also missing at least half my orgs private repos

**Comment by shanemcd** [comment]
Yeah, this sucks. I can't use the app or recommend this to others until it is taken care of.

**Comment by Me1000** [comment]
I've submitted an update, it will allow you to try to add "user/reponame" even if BugHub can't find it on GitHub by look at user's repos. That should get around your problem. Please also confirm that you have issues enabled on your repos.

**Comment by joelparsons** [comment]
Confirmed that I am using issues extensively in all the missing repos.

**Comment by Me1000** [comment]
Alright, hopefully in a few days this will be resolved by just being able to type the repo identifier… if not, I'll contact GitHub, as the only other reason I can think of is that there's an issue in their API. 

Sorry about the issue!

**Comment by Me1000** [comment]
The new update is live on the App Store, please let me know if that solves your issue.

**Comment by joelparsons** [comment]
I can now add my missing repos but they are still missing from the list. Thanks for the fix. I can use the app now
