### ISSUE TITLE
App crashes when adding repos on setup wizard

### ISSUE THREAD

**Issue by joehoyle** [Me1000/issues#66]
When I first launched the app, it asks to add some repos in a wizard style format. I did - checked the repo I wanted to add, when clicking "Next" (can't remember the exact text), the app quit to the homescreen. Only way I was able to get past it was to not add any in the wizard, then just add them as normal from the sidebar.If this isn't a known issue, I can remove the app and try again (presumably I can get an error report from xcode?)

**Comment by Me1000** [comment]
Testflight should give me the trace. I'll let you know if I need anything from you. 

Thanks

**Comment by Me1000** [comment]
This will be fixed in the next beta. Closed.

Thanks!
