### ISSUE TITLE
No visual feedback for "refresh issue" on far right

### ISSUE THREAD

**Issue by joehoyle** [Me1000/issues#67]
I am not sure if this is a bug or whathaveyou. When viewing a single issue, there is a "reload" icon on the far right of te top toolbar - I presume this refreshes the issue for new comments etc, however when I click it, there is no visual indication that it is refreshing. Perhaps the same icon rotating would show it was doing something.

**Comment by Me1000** [comment]
Fixed the in the next beta. Cheers!
