### ISSUE TITLE
Support for private repos

### ISSUE THREAD

**Issue by joehoyle** [Me1000/issues#68]
It seems I can't add a private repo? Is this out of scope for version 1, or is something amiss? The private repo I am trying to add is not mine, but one I have commit access too.

**Comment by Me1000** [comment]
If you load your own repos I think it should show up

**Comment by Me1000** [comment]
Alright, I've looked into the issue. It looks like there is a bug in the Github API. I've filed an issue there... (shame they don't use their own issue tracker).

**Comment by Me1000** [comment]
Update: Github has acknowledged the bug. It should be changed in the near future.

**Comment by Me1000** [comment]
Fixed in the next build.
